### PR TITLE
feat(issue-5): update cmp theme

### LINKED ISSUE #5: suggest cmp theme
suggest cmp theme because I think you like transparent. 😜

image

### PR DESCRIPTION
**Pull request by jisung-lee7**
image

### CODE REVIEW

**Comment by jisung-lee7** [comment]
Screenshot is not good, that is transparent like your theme. 😜

**Comment by jiyeol-lee** [comment]
> Screenshot is not good, that is transparent like your theme. 😜

could you share before vs after video or screenshot?

**Comment by jisung-lee7** [comment]
Okay Im gonna send you when I arrive at home.

**Comment by jisung-lee7** [comment]
> > Screenshot is not good, that is transparent like your theme. 😜
> 
> could you share before vs after video or screenshot?


Here!
[before]
image

[after]
image

**Comment by jiyeol-lee** [comment]
@jskurt So you would like to add border, right? I don't understand "that is transparent like your theme. 😜". Both of before and after screenshot are having a transparent background.

**Comment by jisung-lee7** [comment]
> @jskurt So you would like to add border, right? I don't understand "that is transparent like your theme. 😜". Both of before and after screenshot are having a transparent background.

I mean here haha.

image
image

**Review by jiyeol-lee — APPROVED** [review]

**Comment by jiyeol-lee** [comment]
> > @jskurt So you would like to add border, right? I don't understand "that is transparent like your theme. 😜". Both of before and after screenshot are having a transparent background.
> 
> I mean here haha.
> 
> image image

okay, i think i understand what you mean. it looks good to me. let's merge it.

**Pull request merged**
