### PR TITLE
feat(issue-11): install lualine instead of vim-airline

### LINKED ISSUE #11: install lualine instead of vim-airline
uhm,, You can install this if you want😜

If I have to make an excuse, it's like this.
image

### PR DESCRIPTION
**Pull request by jisung-lee7**

### CODE REVIEW

**Comment by jiyeol-lee** [comment]
@jskurt Can you share a screenshot?

**Comment by jisung-lee7** [comment]
> @jskurt Can you share a screenshot?

Sure, You can see git branch and so cute extension 👍 
image

**Review by jiyeol-lee — APPROVED** [review]

**Comment by jiyeol-lee** [comment]
@jskurt it's same design but smaller package. I like that. thanks

**Comment by jisung-lee7** [comment]
> @jskurt it's same design but smaller package. I like that. thanks

@jiyeol-lee  
I suffered a lot last week to make the design as same as vim-airline as possible.🤣🤣
I'm glad you like it.

**Pull request merged**
